version: '3'
services:
  api_server:
    image: python:3.7-stretch
    restart: always
    volumes:
      - ./api-server:/opt
    links:
      - mongodb
    command: /opt/bin/start.sh

  mongodb:
    image: mongo:3.5
    restart: always
    volumes:
      - ./mongodb/data:/data/db

  nginx:
    image: xcgd/nginx-vts:stable
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - api_server
    ports:
      - "8090:80"
  
  nginx-vts-exporter:
    image: sophos/nginx-vts-exporter
    restart: always
    links:
      - nginx
    environment:
      NGINX_HOST: http://nginx/status/format/json

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always
    links:
      - nginx-vts-exporter

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
        - "3000:3000"
    links:
        - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - ./grafana/data:/var/lib/grafana
