version: '3'
services:
  mongodb:
    image: mongo:3.5
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data:/data/db

  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - api_server
    ports:
      - "8090:80"
  
  api_server:
    image: python:3.7-stretch
    restart: always
    volumes:
      - ./api-server:/opt
    ports:
      - "8088:8088"
    links:
      - mongodb
    command: /opt/bin/start.sh
    
  